# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for 
# more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch

    working_directory: ~/repo
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys: 
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact 
          # match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip setuptools wheel
            pip install -U asynctest sphinx sphinxcontrib-asyncio codecov
            pip install -U -r requirements.txt
      - save_cache:
          paths: 
            - ./venv
          key: v1-dependencies-{{checksum "requirements.txt" }}
        
      # run tests
      - run:
          name: run tests
          command: |
            . venv/bin/activate 
            PYTHONPATH=$PYTHONPATH:$(pwd)
            python3 ./setup.py sdist bdist_egg bdist_wheel
            rm -rf aiowiki
            find dist -name *.whl -exec pip install '{}' +
            python3 tests/__init__.py
            coverage run tests/__init__.py
            codecov
            
      # build docs
      - run:
          name: build documentation
          command: | 
            . venv/bin/activate
            cd docs && make html
      - store_artifacts:
          path: dist
          destination: distributions
          
      - store_artifacts:
          path: docs/_build
          destination: documentation
